version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - database
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: thisisanewpassword
    ports:
      - "3306:3306"
    volumes:
      - ./backend/app.db:/data/app.db
