version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - database
  database:
    image: nouchka/sqlite3:latest
    volumes:
      - ./backend/app.db:/data/app.db
